In [31]:
import folium
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [32]:
# 기본 서울 지도 표시하기
seoul = folium.Map(location=[37.5, 126.98], zoom_start=12) # 37.5, 126.98 위도 경도
seoul

* 각 역별 승하차정보

In [56]:
# 2021 서울지하철 이용객 정보 정규화때문에 두개가 나눠진거다.
data = pd.read_csv("./data/seoul-metro-2021.logs.csv")
data.head()

                       timestamp  station_code  people_in  people_out
0  2021-01-01T05:00:00.000+09:00           150         86          85
1  2021-01-01T06:00:00.000+09:00           150        111         355
2  2021-01-01T07:00:00.000+09:00           150        157         438
3  2021-01-01T08:00:00.000+09:00           150        306         592
4  2021-01-01T09:00:00.000+09:00           150        333         841

In [34]:
# 서울 지하철 역 정보 파일
station_info = pd.read_csv("./data/seoul-metro-station-info.csv")
station_info.head(10)

,station.code,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,station.name_chc,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
0,158,124,1,1호선,지하철1호선,1,청량리(서울시립대입구),청량리|서울시립대입구,祭基洞,祭基洞,Jegidong,チェギドン,37.580178,127.046835,11060,동대문구,서울특별시 동대문구 왕산로 지하205(전농동),서울특별시 동대문구 전농동 620-69 청량리역(1호선),02-6110-1241
1,157,125,1,1호선,지하철1호선,2,제기동,제기동,新設洞,新设洞,Sinseoldong,シンソルトン,37.578103,127.034893,11060,동대문구,서울특별시 동대문구 왕산로 지하93(제기동),서울특별시 동대문구 제기동 65 제기동역(1호선),02-6110-1251
2,156,126,1,1호선,지하철1호선,3,신설동,신설동,東廟앞,东庙,Dongmyo,トンミョアプ,37.575297,127.025087,11060,동대문구,서울특별시 동대문구 왕산로 지하1(신설동),서울특별시 동대문구 신설동 76-5 신설동역(1호선),02-6110-1261
3,159,127,1,1호선,지하철1호선,4,동묘앞,동묘앞,淸凉里(서울市立大入口),清凉里(首尔市立大学),Cheongnyangni(University of Seoul),チョンニャンニ,37.572627,127.016429,11010,종로구,서울특별시 종로구 종로 359(숭인동),서울특별시 종로구 숭인동 117 동묘앞역(1호선),02-6110-1271
4,155,128,1,1호선,지하철1호선,5,동대문,동대문,東大門,东大门,Dongdaemun,トンデムン,37.571420,127.009745,11010,종로구,서울특별시 종로구 종로 지하302(창신동),서울특별시 종로구 창신동 492-1 동대문역(1호선),02-6110-1281
5,154,129,1,1호선,지하철1호선,6,종로5가,종로5가,鍾路5街,钟路五街,Jongno 5(o)ga,チョンノオガ,37.570926,127.001849,11010,종로구,서울특별시 종로구 종로 지하216(종로5가),서울특별시 종로구 종로5가 82-1 종로5가역(1호선),02-6110-1291
6,153,130,1,1호선,지하철1호선,7,종로3가(탑골공원),종로3가|탑골공원,鍾路3街(탑골공원),钟路三街(塔谷公园),Jongno 3(sam)ga,チョンノサムガ,37.571607,126.991806,11010,종로구,서울특별시 종로구 종로 지하129(종로3가),서울특별시 종로구 종로3가 10-5 종로3가역(1호선),02-6110-1301
7,152,131,1,1호선,지하철1호선,8,종각,종각,鐘閣,钟阁,Jonggak,チョンガク,37.570161,126.982923,11010,종로구,서울특별시 종로구 종로 지하55(종로1가),서울특별시 종로구 종로1가 54 종각역(1호선),02-6110-1311
8,151,132,1,1호선,지하철1호선,9,시청,시청,市廳,市厅,City Hall,シチョン,37.564718,126.977108,11020,중구,서울특별시 중구 세종대로 지하101(정동),서울특별시 중구 정동 5-5 시청역(1호선),02-6110-1321
9,150,133,1,1호선,지하철1호선,10,서울역,서울역,서울역,首尔站,Seoul Station,ソウルヨク,37.554648,126.972559,11020,중구,서울특별시 중구 세종대로 지하2(남대문로 5가),서울특별시 중구 남대문로5가 73-6 서울역(1호선),02-6110-1331

In [35]:
data.isna().sum()

timestamp       0
station_code    0
people_in       0
people_out      0
dtype: int64

In [36]:
data.value_counts()

timestamp                      station_code  people_in  people_out
2021-01-01T05:00:00.000+09:00  150           86         85            1
2021-09-01T17:00:00.000+09:00  2549          1427       1201          1
                               2561          284        528           1
                               2560          546        724           1
                               2559          482        568           1
                                                                     ..
2021-05-03T09:00:00.000+09:00  2745          1082       442           1
                               2744          697        528           1
                               2743          1593       768           1
                               2742          895        404           1
2021-12-31T23:00:00.000+09:00  2828          18         34            1
Name: count, Length: 1941553, dtype: int64

In [37]:
station_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   station.code       285 non-null    int64
 1   station.fr_code    285 non-null    object
 2   line.num           285 non-null    int64
 3   line.name          285 non-null    object
 4   line.name_sub      285 non-null    object
 5   line.station_seq   285 non-null    int64
 6   station.name_full  285 non-null    object
 7   station.name       285 non-null    object
 8   station.name_chc   285 non-null    object
 9   station.name_chn   285 non-null    object
 10  station.name_en    285 non-null    object
 11  station.name_jp    285 non-null    object
 12  geo.latitude       285 non-null    float64
 13  geo.longitude      285 non-null    float64
 14  geo.sigungu_code   285 non-null    int64
 15  geo.sigungu_name   285 non-null    object
 16  geo.addres_road    285 non-null    object
 17  geo.address_land   285 non-null    object
 18  geo.phone          285 non-null    object
dtypes: float64(2), int64(4), object(13)
memory usage: 42.4+ KB

각 역 별 승하차 인원 구하기

In [38]:
staion_sum = data.groupby("station_code").sum()

In [39]:
staion_sum.head()

,timestamp,people_in,people_out
station_code,,,
150,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,12697273,12109991
151,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,5997344,6030491
152,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,9638952,9284693
153,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,7704599,7090896
154,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,6651283,6609055

In [40]:
staion_sum2 = staion_sum.drop('timestamp', axis=1)

In [41]:
staion_sum2 # 스테이션 코드에 따른 승차인원, 하차인원

              people_in  people_out
station_code
150            12697273    12109991
151             5997344     6030491
152             9638952     9284693
153             7704599     7090896
154             6651283     6609055
...                 ...         ...
2824            3206211     3097722
2825            1395919     1495603
2826            1614590     1475010
2827            1444073     1147602
2828              41623       46621

[284 rows x 2 columns]

In [42]:
# 지하철 역 정보파일에서 필요한 컬럼만 추출하기

In [43]:
station_info.head(2)

,station.code,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,station.name_chc,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
0,158,124,1,1호선,지하철1호선,1,청량리(서울시립대입구),청량리|서울시립대입구,祭基洞,祭基洞,Jegidong,チェギドン,37.580178,127.046835,11060,동대문구,서울특별시 동대문구 왕산로 지하205(전농동),서울특별시 동대문구 전농동 620-69 청량리역(1호선),02-6110-1241
1,157,125,1,1호선,지하철1호선,2,제기동,제기동,新設洞,新设洞,Sinseoldong,シンソルトン,37.578103,127.034893,11060,동대문구,서울특별시 동대문구 왕산로 지하93(제기동),서울특별시 동대문구 제기동 65 제기동역(1호선),02-6110-1251

In [44]:
# 지하철 역 정보파일에서 필요한 컬럼만 추출하기
station_info = station_info[['station.code', 'line.name_sub', 'geo.latitude', 'geo.longitude']]
station_info

     station.code line.name_sub  geo.latitude  geo.longitude
0             158        지하철1호선     37.580178     127.046835
1             157        지하철1호선     37.578103     127.034893
2             156        지하철1호선     37.575297     127.025087
3             159        지하철1호선     37.572627     127.016429
4             155        지하철1호선     37.571420     127.009745
..            ...           ...           ...            ...
280          2823        지하철8호선     37.451535     127.159816
281          2824        지하철8호선     37.445210     127.156866
282          2825        지하철8호선     37.440918     127.147564
283          2826        지하철8호선     37.437428     127.140722
284          2827        지하철8호선     37.432130     127.129087

[285 rows x 4 columns]

In [45]:
# station_info이 인덱스로 바뀜.
station_info = station_info.set_index('station.code')
station_info

             line.name_sub  geo.latitude  geo.longitude
station.code
158                 지하철1호선     37.580178     127.046835
157                 지하철1호선     37.578103     127.034893
156                 지하철1호선     37.575297     127.025087
159                 지하철1호선     37.572627     127.016429
155                 지하철1호선     37.571420     127.009745
...                    ...           ...            ...
2823                지하철8호선     37.451535     127.159816
2824                지하철8호선     37.445210     127.156866
2825                지하철8호선     37.440918     127.147564
2826                지하철8호선     37.437428     127.140722
2827                지하철8호선     37.432130     127.129087

[285 rows x 3 columns]

In [46]:
staion_sum2

              people_in  people_out
station_code
150            12697273    12109991
151             5997344     6030491
152             9638952     9284693
153             7704599     7090896
154             6651283     6609055
...                 ...         ...
2824            3206211     3097722
2825            1395919     1495603
2826            1614590     1475010
2827            1444073     1147602
2828              41623       46621

[284 rows x 2 columns]

In [47]:
# 인덱스를 이용해서 두개 합치기 : join
joined_data = staion_sum2.join(station_info)
joined_data

              people_in  people_out line.name_sub  geo.latitude  geo.longitude
station_code
150            12697273    12109991        지하철1호선     37.554648     126.972559
151             5997344     6030491        지하철1호선     37.564718     126.977108
152             9638952     9284693        지하철1호선     37.570161     126.982923
153             7704599     7090896        지하철1호선     37.571607     126.991806
154             6651283     6609055        지하철1호선     37.570926     127.001849
...                 ...         ...           ...           ...            ...
2824            3206211     3097722        지하철8호선     37.445210     127.156866
2825            1395919     1495603        지하철8호선     37.440918     127.147564
2826            1614590     1475010        지하철8호선     37.437428     127.140722
2827            1444073     1147602        지하철8호선     37.432130     127.129087
2828              41623       46621        지하철8호선     37.463170     127.139526

[284 rows x 5 columns]

# 지도에 표시하기

In [48]:
# 승차용 서울지도 만들기
seoul_in = folium.Map(location=[37.5, 126.98], zoom_start=12)
seoul_in

In [49]:
# 히트맵 플러그인 모듈
from folium.plugins import HeatMap

In [50]:
joined_data.columns

Index(['people_in', 'people_out', 'line.name_sub', 'geo.latitude',
       'geo.longitude'],
      dtype='object')

In [51]:
# 히트맵 플러그인을 서울 지도에 추가하기
HeatMap(data = joined_data[['geo.latitude','geo.longitude','people_in']]).add_to(seoul_in)
seoul_in

In [53]:
# 하차용 지도 만들고 하차 인원 히트맵에 추가
seoul_out = folium.Map(location=[37.55, 126.98], zoom_start=12)
# 히트맵 플러그인을 서울 지도에 추가하기
HeatMap(data = joined_data[['geo.latitude','geo.longitude','people_out']]).add_to(seoul_out)
seoul_out

# 시간을 추출해서 출퇴근 시간대 혼잡 역 히트맵 그리기

## timestamp를 시간 데이터로 변환하기 
## pd.to_datetime

In [59]:
# timestamp를 시간 데이터로 변환하기 
# pd.to_datetime
data['timestamp'] = pd.to_datetime(data['timestamp'])

In [60]:
# dt.year, month, day, hour, minute, second
data['timestamp'].dt.year

0          2021
1          2021
2          2021
3          2021
4          2021
           ...
1941548    2021
1941549    2021
1941550    2021
1941551    2021
1941552    2021
Name: timestamp, Length: 1941553, dtype: int32

In [61]:
from datetime import datetime

In [63]:
today = datetime.today()

In [64]:
today.year

2023

In [66]:
str(today.year) + str(today.month) + str(today.day)

'20231030'

In [87]:
# 오전 9시 이전 데이터
morning_data = data[data['timestamp'].dt.hour < 9]

In [88]:
morning_data

                        timestamp  station_code  people_in  people_out
0       2021-01-01 05:00:00+09:00           150         86          85
1       2021-01-01 06:00:00+09:00           150        111         355
2       2021-01-01 07:00:00+09:00           150        157         438
3       2021-01-01 08:00:00+09:00           150        306         592
19      2021-01-01 05:00:00+09:00           151         43          40
...                           ...           ...        ...         ...
1941518 2021-12-31 08:00:00+09:00          2827        391         311
1941534 2021-12-31 05:00:00+09:00          2828         20          10
1941535 2021-12-31 06:00:00+09:00          2828         83          41
1941536 2021-12-31 07:00:00+09:00          2828        279         119
1941537 2021-12-31 08:00:00+09:00          2828        347         375

[408748 rows x 4 columns]

In [73]:
# 퇴근용 데이터 추출
evening_data = data[data['timestamp'].dt.hour > 18]
evening_data

                        timestamp  station_code  people_in  people_out
14      2021-01-01 19:00:00+09:00           150        579         425
15      2021-01-01 20:00:00+09:00           150        479         354
16      2021-01-01 21:00:00+09:00           150        510         307
17      2021-01-01 22:00:00+09:00           150        445         134
18      2021-01-01 23:00:00+09:00           150        101          77
...                           ...           ...        ...         ...
1941548 2021-12-31 19:00:00+09:00          2828         74         263
1941549 2021-12-31 20:00:00+09:00          2828         73         145
1941550 2021-12-31 21:00:00+09:00          2828         95         209
1941551 2021-12-31 22:00:00+09:00          2828         54         138
1941552 2021-12-31 23:00:00+09:00          2828         18          34

[510935 rows x 4 columns]

In [75]:
morning_data.drop('timestamp', axis=1, inplace=True)
evening_data.drop('timestamp', axis=1, inplace=True)

C:\Users\hi\AppData\Local\Temp\ipykernel_11620\415749048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  morning_data.drop('timestamp', axis=1, inplace=True)
C:\Users\hi\AppData\Local\Temp\ipykernel_11620\415749048.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evening_data.drop('timestamp', axis=1, inplace=True)

In [79]:
morning_station_sum = morning_data.groupby('station_code').sum()
evening_station_sum = evening_data.groupby('station_code').sum()

In [78]:
morning_station_sum

              people_in  people_out
station_code
150             2933591     1503741
151             1710997      243533
152             3134030      393697
153             2087555      379890
154             1361369      293036
...                 ...         ...
2824             295188      987423
2825             157323      423737
2826             147735      436284
2827             217374      201216
2828               4919       12920

[284 rows x 2 columns]

In [83]:
evening_station_sum

              people_in  people_out
station_code
150             2933591     1503741
151             1710997      243533
152             3134030      393697
153             2087555      379890
154             1361369      293036
...                 ...         ...
2824             295188      987423
2825             157323      423737
2826             147735      436284
2827             217374      201216
2828               4919       12920

[284 rows x 2 columns]

In [80]:
morning_joined_data = morning_station_sum.join(station_info)
evening_joined_data = evening_station_sum.join(station_info)

In [81]:
morning_joined_data.head()

              people_in  people_out line.name_sub  geo.latitude  geo.longitude
station_code
150             1280861     3455240        지하철1호선     37.554648     126.972559
151              215072     2744871        지하철1호선     37.564718     126.977108
152              221218     3643820        지하철1호선     37.570161     126.982923
153              218777     1222960        지하철1호선     37.571607     126.991806
154              185510     1776080        지하철1호선     37.570926     127.001849

In [82]:
evening_joined_data.head()

              people_in  people_out line.name_sub  geo.latitude  geo.longitude
station_code
150             2933591     1503741        지하철1호선     37.554648     126.972559
151             1710997      243533        지하철1호선     37.564718     126.977108
152             3134030      393697        지하철1호선     37.570161     126.982923
153             2087555      379890        지하철1호선     37.571607     126.991806
154             1361369      293036        지하철1호선     37.570926     127.001849

In [84]:
# 출근시간용 지도 만들고 승차 인원 히트맵 지도에 표시하기
# 출근 시간용 

seoul_morning_in = folium.Map(location=[37.55, 126.98], zoom_start=12)
# 히트맵 플러그인을 서울 지도에 추가하기
HeatMap(data = morning_joined_data[['geo.latitude','geo.longitude','people_in']]).add_to(seoul_morning_in)
seoul_morning_in

In [85]:
# 출근시간용 지도 만들고 승차 인원 히트맵 지도에 표시하기
# 출근 시간용 하차

seoul_evening_out = folium.Map(location=[37.55, 126.98], zoom_start=12)
# 히트맵 플러그인을 서울 지도에 추가하기
HeatMap(data = evening_joined_data[['geo.latitude','geo.longitude','people_out']]).add_to(seoul_evening_out)
seoul_evening_out

In [99]:
# 점심시간에 가장 많이 탑승/ 하차하는 곳 히트맵 11-13
lunchtime = data.loc[(data['timestamp'].dt.hour >= 11) & (data['timestamp'].dt.hour <= 13)]

In [100]:
lunchtime.drop('timestamp', axis=1, inplace=True)

C:\Users\hi\AppData\Local\Temp\ipykernel_11620\2002967634.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lunchtime.drop('timestamp', axis=1, inplace=True)

In [98]:
lunchtime

         station_code  people_in  people_out
7                 150        737         838
26                151        190         223
45                152        340         400
64                153        472         543
83                154        293         391
...               ...        ...         ...
1941465          2824        517         382
1941484          2825        230         216
1941503          2826        291         210
1941522          2827        232         194
1941541          2828        192         124

[102187 rows x 3 columns]

In [102]:
lunchdata_sum = lunchtime.groupby('station_code').sum()

In [103]:
lunchdata_sum

              people_in  people_out
station_code
150             1901107     1812718
151              547615      888307
152              948445     1434214
153             1281857     1901932
154             1123303     1565247
...                 ...         ...
2824             465690      320849
2825             222537      197038
2826             263669      194111
2827             250721      215515
2828               7013        5513

[284 rows x 2 columns]

In [104]:
lunch_joined_data = lunchdata_sum.join(station_info)

In [ ]:
# 런치 승차

In [106]:
seoul_lunch_in = folium.Map(location=[37.55, 126.98], zoom_start=12)

In [107]:
lunchtime_in = folium.Map(location=[37.55, 126.98], zoom_start=12)
HeatMap(data = lunch_joined_data[['geo.latitude','geo.longitude','people_in']]).add_to(seoul_lunch_in)
seoul_lunch_in

In [108]:
seoul_lunchtime_out = folium.Map(location=[37.55, 126.98], zoom_start=12)
HeatMap(data = lunch_joined_data[['geo.latitude','geo.longitude','people_out']]).add_to(seoul_lunchtime_out)
seoul_lunchtime_out